### ISSUE TITLE
Failure in demo example

### ISSUE THREAD

**Issue by ricl** [meteostat/dev#10]
The endpoint in your documentation for bulk data transfers does not appear to work

curl "https://bulk.meteostat.net/v2/hourly/10637.csv.gz" --output "10637.csv.gz"

returns a 404 instead of the expected gz file

**Comment by clampr** [comment]
Thanks! Fixed.

**Comment by ricl** [comment]
No it's not. Just tried it and it  still fails with a 404. Is there a time delay I should wait before it is OK?

**Comment by ricl** [comment]
C:\Users\richa\curl "https://bulk.meteostat.net/v2/hourly/01001.csv.gz" --output "C:\Users\richa\source\repos\Get Meteosat data\GZ\01001.csv.gz"
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   402    0   402    0     0    402      0 --:--:-- --:--:-- --:--:--  3216

**Comment by ricl** [comment]
Tried it without the spaces in the output file name too

C:\Users\richa\source\repos\Get Meteosat data\bin\Debug\net5.0>curl "https://bulk.meteostat.net/v2/hourly/01001.csv.gz" --output "C:\Users\richa\source\repos\01001.csv.gz"
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   402    0   402    0     0    402      0 --:--:-- --:--:-- --:--:--  3688

**Comment by clampr** [comment]
Sorry, I meant I fixed the error in the docs. Please try with the updated example:

```sh
curl "https://bulk.meteostat.net/v2/hourly/full/10637.csv.gz" --output "10637.csv.gz"
```

**Comment by ricl** [comment]
Yup. That worked for me. Thanks

**Comment by ricl** [comment]
Except the database does not contain a station Id
	
1926-01-03 | 6 | 8.9 | 6.7 | 86 |  |  |  | 9.4 |  | 1007.9

**Comment by ricl** [comment]
Cancel that. Of course the name IS the id. Duh!
