### ISSUE TITLE
Null values in the data when asking for cities in France.

### ISSUE THREAD

**Issue by luclagarde83** [meteostat/dev#9]
For the data in Berlin for exemple, there is not problems, but for Paris for instance, most of the value are null.

**Comment by clampr** [comment]
Can you provide the code snippet?

**Comment by clampr** [comment]
Ok, I see. That's expected behaviour as data is only available if nearby stations did report data to Meteostat which not seems to be the case here. It might make sense to add the french weather service to our import routines if they provide any open data.
